version: '3.4'

services:
  plex:
    container_name: plex
    hostname: PlexVids
    image: plexinc/pms-docker:latest

    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=claim-39aQ7sHgF7RQndTE4gXs
      - ADVERTISE_IP=http://192.168.1.22:32400/

    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"

    volumes:
      - /mnt/d/Plex/config:/config
      - /mnt/d/Plex/transcode:/transcode
      - /mnt/x/Vids:/data/Vids
